# Generated by Django 3.1.5 on 2021-01-07 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainImage', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 1, 7, 12, 36, 3, 513495))),
                ('rotateAngle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('imagePostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_app.imagepost')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('rotateAngle', models.IntegerField()),
                ('imagePostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_app.imagepost')),
            ],
        ),
    ]
