# Generated by Django 3.1.5 on 2021-01-07 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0002_auto_20210107_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
