# Generated by Django 3.1.5 on 2021-01-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0004_auto_20210108_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='mainImage',
        ),
    ]
